		try {
            int result = s1.compute(A, B);
            cout << result << endl;
        } catch (const invalid_argument& e) {
            cout << "Exception: " << e.what() << endl;
        } catch (const bad_alloc& e) {
            cout << "Not enough memory" << endl;
        } catch (const exception& e) {
            cout << "Exception: " << e.what() << endl;
        } catch (...) {
            cout << "Other Exception" << endl;
        }
 
